name: davina_money_record
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  d_chart: ^0.0.4
  d_info: ^0.0.7
  d_input: ^0.0.2
  d_method: ^0.0.2
  d_view: ^0.0.3
  flutter:
    sdk: flutter
  gap: ^3.0.1
  get: ^4.6.5
  http: ^0.13.4
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - asset/
